### ISSUE TITLE
Unable to cast object of type 'System.String' to type 'System.Int32'.

### ISSUE THREAD

**Issue by dm1lk** [Sprixitite/DELTARUNE-Save-Utility-Public#1]
# How To Reproduce
- Open the x64 Self-Contained Program.
- Select Chapter Two.
- Select "[Default] Before Final Boss" on Save 3.
- Click "Save Current File"
- Profit
# Stacktrace
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Int32'.
   at DSU.MainWindow.SaveCurrentFileInSaveSlot(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.21.41101
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Private.CoreLib.dll
----------------------------------------
DSU
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/DSU.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.121.40306
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.ComponentModel.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 4.0.2.2
    Win32 Version: 4.700.21.6905
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Drawing.Common.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Collections.NonGeneric.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Diagnostics.TraceSource.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.ObjectModel.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Runtime
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Runtime.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Threading.Thread.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Runtime.InteropServices.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.121.40306
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/Accessibility.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.ComponentModel.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.19.56404
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Linq
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Linq.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 4.0.6.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Private.Uri.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.IO.FileSystem.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Threading
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Threading.dll
----------------------------------------
System.Collections
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Collections.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 4.0.15.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Collections.Concurrent.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 1.4.5.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 1.2.5.0
    Win32 Version: 4.700.21.41603
    CodeBase: file:///C:/Users/jam3s/AppData/Local/Temp/.net/DSU/ifjj3irp.x4b/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************
```

**Comment by Sprixitite** [comment]
I've fixed the issue, but I've ran into another where some save paths are linking for some reason
This is why we don't change our save management 10 minutes before release
I'll mark this as closed and have a hotfix out within a day
